import { resolveChromium } from './token-extractor.mjs';
const chromium = await resolveChromium();
const b = await chromium.launch({args:['--force-color-profile=srgb','--disable-gpu']});
const page = await (await b.newContext({viewport:{width:1440,height:900}})).newPage();
await page.goto('http://localhost:8879/suborganisms/SO-3-nature-place/index.html',{waitUntil:'networkidle'});
await page.waitForFunction(()=>window.__SO3_OK__===true,{timeout:8000}).catch(()=>{});
const total = await page.evaluate(()=>document.documentElement.scrollHeight-innerHeight);
await page.evaluate(yy=>window.scrollTo(0,yy), Math.round(0.535*total));
await page.waitForTimeout(800);
await page.screenshot({path:'/private/tmp/claude-501/-Users-yehorfedorov-Downloads-KAI/c3be139d-c516-47c2-a8d3-42fb9aeac5b3/scratchpad/odo-nogpu.png', clip:{x:900,y:150,width:540,height:700}});
await b.close();
