#!/usr/bin/env node
/* ============================================================================
   library-index.mjs — emit INDEX.json + INDEX.md + COVERAGE.md from every
   front-matter in library/. GENERATED-ONLY: never hand-edit the outputs.
   Run:  node scripts/library-index.mjs
   No deps (uses scripts/lib-frontmatter.mjs).
   ========================================================================== */
import { readdirSync, statSync, writeFileSync, existsSync, readFileSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readRecipe } from './lib-frontmatter.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const LIB = join(ROOT, 'library');
const REGISTRY = join(ROOT, 'skills', 'grammar', 'references', '_REGISTRY_TID.md');

function dirs(p) {
  if (!existsSync(p)) return [];
  // _-prefixed dirs are infrastructure (e.g. combos/_scaffold), not library entries — skip them
  return readdirSync(p).filter(n => !n.startsWith('_') && statSync(join(p, n)).isDirectory());
}

function collectVariants(compDir) {
  const vRoot = join(compDir, 'variants');
  if (!existsSync(vRoot)) return [];
  return dirs(vRoot).map(v => {
    const r = readRecipe(join(vRoot, v, 'variant.recipe.md')) || {};
    return { id: r.variant || v, status: r.status || 'seed', extends: r.extends };
  });
}

const entries = [];

// components
for (const id of dirs(join(LIB, 'components'))) {
  const d = join(LIB, 'components', id);
  const fm = readRecipe(join(d, 'RECIPE.md'));
  if (!fm) continue;
  const variants = collectVariants(d);
  entries.push({ ...fm, _path: `library/components/${id}/`, _variantsResolved: variants });
}
// combos
for (const id of dirs(join(LIB, 'combos'))) {
  const d = join(LIB, 'combos', id);
  const fm = readRecipe(join(d, 'RECIPE.md'));
  if (!fm) continue;
  entries.push({ ...fm, _path: `library/combos/${id}/`, _variantsResolved: [] });
}
// shared utils
for (const id of dirs(join(LIB, 'shared'))) {
  const d = join(LIB, 'shared', id);
  const fm = readRecipe(join(d, 'UTIL.md'));
  if (!fm) continue;
  entries.push({ ...fm, _path: `library/shared/${id}/`, _variantsResolved: [] });
}

entries.sort((a, b) => {
  const la = String(a.level), lb = String(b.level);
  if (la !== lb) return la < lb ? -1 : 1;
  return String(a.id) < String(b.id) ? -1 : 1;
});

/* ---- INDEX.json (the machine entry point, keyed by id) ---- */
const json = {};
for (const e of entries) json[e.id] = e;
writeFileSync(join(LIB, 'INDEX.json'), JSON.stringify(json, null, 2) + '\n');

/* ---- INDEX.md (human mirror) ---- */
const arr = v => Array.isArray(v) ? v.join(',') : (v == null ? '' : String(v));
const meaningOneLiner = e => {
  const w = e.meaning?.when || '';
  const l = e.meaning?.lands || '';
  const s = `${w} → ${l}`.replace(/\|/g, '/');
  return s.length > 120 ? s.slice(0, 117) + '…' : s;
};
const variantNames = e => (e._variantsResolved || []).map(v => v.id).join(',') || arr(e.variants) || '—';
let md = `<!-- AUTO-GENERATED by scripts/library-index.mjs — DO NOT HAND-EDIT. -->\n`;
md += `# library INDEX\n\nOne row per technique. \`section-builder\` parses \`INDEX.json\`; this MD is the human mirror.\n\n`;
md += `| id | name | kind | lvl | status | webgl | beat | path | entry.call | variants | owns_pin | timing | combines_with | gated_by | registry | meaning (when → lands) |\n`;
md += `|----|------|------|-----|--------|-------|------|------|-----------|----------|----------|--------|---------------|----------|----------|------------------------|\n`;
for (const e of entries) {
  md += `| ${e.id} | ${e.name||''} | ${e.kind||''} | ${e.level??''} | ${e.status||''} | ${e.webgl?'yes':'no'} | ${arr(e.page_beat)} | ${e._path} | ${e.entry?.call||(e.uses?'(uses…)':'')} | ${variantNames(e)} | ${e.owns_pin?'yes':'no'} | ${arr(e.timing_layer)} | ${arr(e.combines_with)} | ${arr(e.gated_by)} | ${arr(e.source?.registry_ref)} | ${meaningOneLiner(e)} |\n`;
}
writeFileSync(join(LIB, 'INDEX.md'), md);

/* ---- registry T-ID coverage (brain ↔ body, both directions) ----
   Parse every `| T-NNN` row out of _REGISTRY_TID.md, then cross it with the
   union of `source.registry_ref` cited by library entries. Two gaps surface:
     A. registry T-IDs with NO library impl  → the build backlog (the brain
        names a move the body cannot yet reproduce).
     B. entries citing a registry_ref that is NOT a real registry T-ID → a
        dangling brain-link (typo / removed row) to reconcile.                */
function registryTids() {
  if (!existsSync(REGISTRY)) return null;
  const txt = readFileSync(REGISTRY, 'utf8');
  const ids = new Set();
  for (const m of txt.matchAll(/^\|\s*(T-\d+)\b/gm)) ids.add(m[1]);
  return ids;
}
const regIds = registryTids();
const citedRefs = new Map(); // ref -> [entry ids]
for (const e of entries) {
  const r = e.source && e.source.registry_ref;
  if (!Array.isArray(r)) continue;
  for (const ref of r) {
    if (!citedRefs.has(ref)) citedRefs.set(ref, []);
    citedRefs.get(ref).push(e.id);
  }
}
const coveredTids = regIds ? [...citedRefs.keys()].filter(t => regIds.has(t)).sort() : [];
const uncoveredTids = regIds ? [...regIds].filter(t => !citedRefs.has(t)).sort() : [];
const danglingRefs = regIds ? [...citedRefs.keys()].filter(t => /^T-\d+$/.test(t) && !regIds.has(t)).sort() : [];

/* ---- COVERAGE.md (backlog + orphans + registry coverage) ---- */
const officialCount = entries.filter(e => e.status === 'official').length;
const noRegistry = entries.filter(e => e.kind === 'component' && (!e.source?.registry_ref || e.source.registry_ref.length === 0));
const seeds = entries.filter(e => e.status === 'seed' || e.status === 'wip');
let cov = `<!-- AUTO-GENERATED by scripts/library-index.mjs — DO NOT HAND-EDIT. -->\n`;
cov += `# library COVERAGE\n\n`;
cov += `- Total entries: **${entries.length}** (components+combos+shared-utils)\n`;
cov += `- status:official: **${officialCount}**\n`;
cov += `- status:seed/wip (build backlog): **${seeds.length}**\n`;
if (regIds) {
  cov += `- registry T-IDs total: **${regIds.size}** · implemented by library: **${coveredTids.length}** · not yet implemented: **${uncoveredTids.length}**\n`;
}
cov += `\n## Registry T-IDs IMPLEMENTED by library (brain → body, the down-link)\n`;
if (!regIds) cov += `- (registry not found at ${REGISTRY.replace(ROOT + '/', '')})\n`;
else if (coveredTids.length === 0) cov += `- none\n`;
else for (const t of coveredTids) cov += `- \`${t}\` → ${citedRefs.get(t).map(i => `\`${i}\``).join(', ')}\n`;

cov += `\n## Registry T-IDs WITHOUT impl (the technique-recording backlog — ${uncoveredTids.length})\n`;
if (!regIds) cov += `- (registry not found)\n`;
else if (uncoveredTids.length === 0) cov += `- none — full brain coverage\n`;
else cov += uncoveredTids.map(t => `\`${t}\``).join(' ') + '\n';

if (danglingRefs.length) {
  cov += `\n## ⚠ Dangling brain-links (entry cites a registry_ref not in the registry — fix)\n`;
  for (const t of danglingRefs) cov += `- \`${t}\` cited by ${citedRefs.get(t).map(i => `\`${i}\``).join(', ')}\n`;
}

cov += `\n## Backlog (seed / wip — not yet reproducible-official)\n`;
for (const e of seeds) cov += `- \`${e.id}\` (${e.kind}, ${e.status}) — ${e._path}\n`;
cov += `\n## Orphans (component with no source.registry_ref → reconcile to the brain)\n`;
if (noRegistry.length === 0) cov += `- none\n`;
for (const e of noRegistry) cov += `- \`${e.id}\` — ${e._path}\n`;
writeFileSync(join(LIB, 'COVERAGE.md'), cov);

console.log(`[library-index] wrote INDEX.json (${entries.length} rows), INDEX.md, COVERAGE.md`);
